version: "3.7"
services:
  clickhouse-manager-app:
    container_name: clickhouse-manager-app
    image: clickhouse-manager-app:1.0.1
    ports:
      - 8760:7012
    env_file:
      - ./.env
    network_mode: bridge
